adding requirements asked here: https://github.com/geosolutions-it/De…
geosolutions-it/docker-geoserver pull request #27
Opened 2020-12-09 17:11 UTC by lpasquali

…vOps/issues/391

2020-12-13 11:29 UTC, randomorder requested changes
looks good please fix the typo and swap the postgresql client application

2020-12-13 11:29 UTC, randomorder commented on Dockerfile
> +  ${EXTRA_OPT}"
supposed to be EXTRA_OPT**S**

2020-12-13 11:29 UTC, randomorder commented on Dockerfile
> +RUN apt-get update && apt-get install --yes gdal-bin pgcli fontconfig libfreetype6
use postgresql-client instead og pgcli please

2020-12-14 14:56 UTC, randomorder commented
Please also switch base image like I did [here](https://github.com/geosolutions-it/docker-geoserver/blob/docker_hub_build/Dockerfile#L1)

Because of this: 
![image](https://user-images.githubusercontent.com/5264230/102096216-bd439600-3e24-11eb-8ad4-91a798c0ef2e.png)

2020-12-15 10:03 UTC, lpasquali commented
latest commits should fix everything you requested @randomorder

2020-12-15 10:19 UTC, randomorder approved these changes

2020-12-15 10:19 UTC, merged