Fixed issue with the catalina_wrapper.sh
geosolutions-it/docker-geoserver pull request #47
Opened 2021-02-23 14:19 UTC by agpenton

Resolves #46 
- catalina_wrapper.sh added to Dockerfile.
- added creation of plugins folder in custom_build.sh
- added .dockerignore file

2021-02-23 14:35 UTC, randomorder requested changes
- Some changes are ok
- Some are project specific and shouldn't end up on master. Please use a dedicated branch with the project code
- Some changes are not directly related with catalina_wrapper and is not clear why you're making them. Plese create separate issues and separate PRs as needed

2021-02-23 14:35 UTC, randomorder commented on custom_build.sh
> +    download_plugin ext libjpeg-turbo
please remove this

2021-02-23 14:35 UTC, randomorder commented on custom_build.sh
> +    download_plugin ext feature-pregeneralized
not on master. Use a project specific branch instead

2021-02-23 14:35 UTC, randomorder commented on custom_build.sh
> +    download_plugin ext css
not on master. Use a project specific branch instead

2021-02-23 14:35 UTC, randomorder commented on custom_build.sh
> +	${DOCKER_BUILD_COMMAND} --build-arg GEOSERVER_WEBAPP_SRC=${GEOSERVER_ARTIFACT_DIRECTORY}/geoserver.war \
why this change?

2021-02-23 14:35 UTC, randomorder commented on custom_build.sh
> +	${DOCKER_BUILD_COMMAND} --build-arg GEOSERVER_WEBAPP_SRC=${GEOSERVER_ARTIFACT_DIRECTORY}/geoserver.war \
why this change?

2021-02-23 14:35 UTC, randomorder commented on Dockerfile
> +#COPY --from=mother "/output/webapp/geoserver" "${CATALINA_BASE}/webapps/geoserver"
why this change?

2021-02-24 08:51 UTC, agpenton reviewed
there are the answers to the changes.

2021-02-24 08:51 UTC, agpenton commented on custom_build.sh
> +    download_plugin ext libjpeg-turbo
is the branch ready to create the PR?

2021-02-24 11:34 UTC, closed without merging